name: clubs_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - scipy>=1.11.0
  - kneed>=0.8.5
  - seaborn>=0.12.0
  - matplotlib>=3.7.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pip
  - pip:
    - -r requirements.txt 